<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="DBUserModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Photo" Member="Photo">
    <Type Name="Photo">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Photos" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IdDog" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Pieski_Photo" Member="Pieski" ThisKey="IdDog" OtherKey="Id" Type="Pieski" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Pieski" Member="Pieski">
    <Type Name="Pieski">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Rasa" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Imie" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Wiek" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Plec" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Zdjecie" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Aktywny" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[Lubi dzieci]" Member="Lubi_dzieci" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[Lubi psy]" Member="Lubi_psy" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Opis" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IdUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Pieski_Photo" Member="Photo" ThisKey="Id" OtherKey="IdDog" Type="Photo" />
      <Association Name="Pieski_Like" Member="Like" ThisKey="Id" OtherKey="LikeDog" Type="Like" />
      <Association Name="Pieski_FormSchel" Member="FormSchel" ThisKey="Id" OtherKey="idDog" Type="FormSchel" />
      <Association Name="User_Pieski" Member="User" ThisKey="IdUser" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Like]" Member="Like">
    <Type Name="Like">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LikeDog" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Pieski_Like" Member="Pieski" ThisKey="LikeDog" OtherKey="Id" Type="Pieski" IsForeignKey="true" />
      <Association Name="User_Like" Member="User" ThisKey="IdUser" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="User">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PASSWORD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ROLE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PHOTO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PHONE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ADDRESS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DESCRIPTION" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="User_Pieski" Member="Pieski" ThisKey="Id" OtherKey="IdUser" Type="Pieski" />
      <Association Name="User_Like" Member="Like" ThisKey="Id" OtherKey="IdUser" Type="Like" />
      <Association Name="User_Blog" Member="Blog" ThisKey="Id" OtherKey="author" Type="Blog" />
      <Association Name="User_Comments" Member="Comments" ThisKey="Id" OtherKey="author" Type="Comments" />
      <Association Name="User_FormSchel" Member="FormSchel" ThisKey="Id" OtherKey="idUser" Type="FormSchel" />
    </Type>
  </Table>
  <Table Name="dbo.PhotosBlog" Member="PhotosBlog">
    <Type Name="PhotosBlog">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PhotosPost" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IdPost" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Blog_PhotosBlog" Member="Blog" ThisKey="IdPost" OtherKey="Id" Type="Blog" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Blog" Member="Blog">
    <Type Name="Blog">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="author" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="photo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Blog_PhotosBlog" Member="PhotosBlog" ThisKey="Id" OtherKey="IdPost" Type="PhotosBlog" />
      <Association Name="Blog_Comments" Member="Comments" ThisKey="Id" OtherKey="IdPost" Type="Comments" />
      <Association Name="User_Blog" Member="User" ThisKey="author" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Comments" Member="Comments">
    <Type Name="Comments">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="author" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="comment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IdPost" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_Comments" Member="User" ThisKey="author" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="Blog_Comments" Member="Blog" ThisKey="IdPost" OtherKey="Id" Type="Blog" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FormSchel" Member="FormSchel">
    <Type Name="FormSchel">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="surname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="message" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="idDog" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_FormSchel" Member="User" ThisKey="idUser" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="Pieski_FormSchel" Member="Pieski" ThisKey="idDog" OtherKey="Id" Type="Pieski" IsForeignKey="true" />
    </Type>
  </Table>
</Database>